config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]

  root 'subjects#about'

  get '/about' => 'subjects#about'
  get '/resources' => 'subjects#resources'
  post 'subjects/search' => 'subjects#search', as: 'search_subjects'
  get '/random' => 'subjects#random', as: 'sample_subject'
  resources :subjects

end

app/models/subject.rb
require 'open-uri'
require 'nokogiri'

class Subject < ActiveRecord::Base
  belongs_to :user

  def has_page?(url)
    begin
      html = open(url)
      true
    rescue OpenURI::HTTPError => e
      if e.message == '404 Not Found'
        false
      end
    end
  end

  def sort_name
    name_array = self.name.split(' ').reverse!
    result = name_array.shift
    name_array.reverse!
    for i in 0...name_array.length
      result << name_array[i]
    end
    result.capitalize!
  end

  def pull_tweets
    tweets = []
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["twitter_key"]
      config.consumer_secret = ENV["twitter_secret"]
    end
    client.search(self.name, result_type: type = "mixed", lang: "en").take(10).each do |tweet|
      html = client.oembed(tweet.id).html
      tweets << html if !tweets.include?(html) && tweet.text.include?(self.name)
    end
    tweets
  end

  def pull_articles
    base_url = "http://api.nytimes.com/svc/search/v2/articlesearch.json?q="
    q = self.name.gsub(" ","+")
    json = JSON.load(open(base_url + q + "&sort=newest&api-key=#{ENV["nyt_key"]}"))
    json["response"]["docs"].first(5)
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to  :subject
  validates  :html, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new]

  def about
  end

  def index
    @subjects_with = Subject.where(:has_wiki_page => true).order(:sort_name)
    @subjects_without = Subject.where(:has_wiki_page => false).order(:sort_name)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def search
    @subject = Search.new(params[:query]).search
    if @subject
      redirect_to subject_path(@subject)
    else
      flash[:message] = "We couldn't find #{params[:query]}."
      redirect_to sample_subject_path
    end
  end

  def create
    name = params[:subject][:name].split(' ').collect {|n| n.capitalize!}.join(' ')
    @subject = Subject.create(name: name, user_id: current_user.id)
    @subject.sort_name = @subject.sort_name
    @subject.save
    binding.pry

    sanitized_name = @subject.name
    sanitized_name.gsub!(/ë/, 'e')
    sanitized_name.gsub!(/ö/, 'o')
    sanitized_name.gsub!(/ğ/, 'g')
    sanitized_name.gsub!(/Ö/, 'O')

    base_wiki_url = "http://en.wikipedia.org/wiki/#{sanitized_name.gsub(" ", "_")}"
    
    if @subject.has_page?(base_wiki_url)
      data = Nokogiri::HTML(open(base_wiki_url))
      bio_text = data.css("div#mw-content-text p:nth-child(2)").text.gsub(/\[[0-9]+\]/, '')
      if !bio_text.empty?
        @subject.bio = bio_text + "  (Source: Wikipedia)"
      end
      @subject.wiki_page_link = base_wiki_url
      @subject.has_wiki_page = true
    else
      @subject.has_wiki_page = false
      @subject.wiki_create_link = "https://en.wikipedia.org/w/index.php?title=#{sanitized_name.gsub(" ", "_")}&action=edit"
    end
    @subject.save

    redirect_to subject_path(@subject)
  end

  def new
    @subject = Subject.new
  end

  def random
    ids = Subject.pluck(:id)
    @subject = Subject.find(ids.sample)
    render 'show'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  ADMIN = [1, 3]

  def index
    @users = User.all
    unless ADMIN.include?(current_user.id)
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def show
    @user = User.find(params[:id])
    unless ADMIN.include?(current_user.id)
      redirect_to root_path, :alert => "Access denied."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container">
    <div class="footer-text">Made by <a href="http://www.github.com/agoldvarg">Alex Goldvarg</a>, <a href="http://www.github.com/superandrew123">Andrew Miksch</a> & <a href="http://www.github.com/rnackman">Rachel Nackman</a> at <a href="http://www.flatironschool.com">Flatiron School</a>. | <a href="http://www.github.com/agoldvarg/code-equality">See our source code.</a> | <a href="mailto: hello@codeequality.com">We love feedback!</a></div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-search">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">=CodeEquality=</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-search">
      <%= form_tag(search_subjects_path, :class => "navbar-form navbar-right", :role => "search")  do %>
        <input id="searchbar" name="query" placeholder=" Enter Name Here..." type="text">
        <button type="submit" class="btn btn-default">Search</button>
        <% if !user_signed_in? %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-default' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default' %>
        <% else %>
          <%= link_to 'Edit Account', edit_user_registration_path, class: 'btn btn-default' %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <h5 class="nav navbar-nav navbar-right">Welcome, <%= current_user.name %>!</h5>
      <% end %>

      <ul class="nav navbar-nav navbar-left">
        <li><a href="/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="/subjects">Index</a></li>
        <li><a href="/resources">Resources</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeEquality</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <% flash.each do |key, value| %>
    <% unless key == "message" %>
      <div class="alert alert-dismissible alert-<%= key %>">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= value %>
      </div>
    <% end %>
  <% end %>
  <div class="container main">
    <% if params[:action] == 'random' %>
      <div class="refresh-button">
        <a href="/random">
          <span class="glyphicon glyphicon-refresh"></span>
          <h5>See another woman in technology.</h5>
        </a>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/subjects/_article.html.erb
<% @subject.pull_articles.each do |article| %>
  <span><%= link_to article["headline"]["main"], url_for(article["web_url"]), target: "_blank" %></span><br>
<% end %>

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.submit "Add Individual", class: 'btn btn-primary' %>
<% end %>

app/views/subjects/_subject.html.erb
<li><%= link_to subject.name, subject_path(subject) %></li>

app/views/subjects/_subject_with_wiki.html.erb
<div class="jumbotron">
  <h1><%= @subject.name.upcase %></h1>
  <h2>HAS A WIKIPEDIA PAGE</h2>
  <h3><%= link_to "Help make it better!", @subject.wiki_page_link, target: "_blank" %></h3>
</div>

<div class="row top-pad">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-body" id="bio-div">
        <h3 id="bio-text"><%= @subject.bio %></h3>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-5">
    <div class="panel">
      <div class="panel-header">
        <h3>RECENT ARTICLES - NEW YORK TIMES</h3>
      </div>
      <div class="panel-body" id="articles-panel">
        <%= render 'subjects/article', subject: @subject %>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="panel">
      <div class="panel-header">
        <h3>RECENT ACTIVITY FROM TWITTER:</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <%= render 'subjects/tweet', subject: @subject %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/_subject_without_wiki.html.erb
<div class="jumbotron">
  <h1><%= @subject.name.upcase %></h1>
  <h2>NEEDS A WIKIPEDIA PAGE</h2>
  <h3><%= link_to "Help get it started!", @subject.wiki_create_link, target: "_blank" %></h3>
</div>

<div class="row top-pad">
  <div class="col-md-5">
    <div class="panel">
      <div class="panel-header">
        <h3>RECENT ARTICLES - NEW YORK TIMES</h3>
      </div>
      <div class="panel-body" id="articles-panel">
        <%= render 'subjects/article', subject: @subject %>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="panel">
      <div class="panel-header">
        <h3>RECENT ACTIVITY FROM TWITTER:</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
          <%= render 'subjects/tweet', subject: @subject %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/_tweet.html.erb
<% @subject.pull_tweets.each do |tweet| %>
  <%= tweet.html_safe %>    
<% end %>

app/views/subjects/about.html.erb
<div class="jumbotron">
  <p><h1>Women in technology are<br>under-represented on Wikipedia.</h1></p>
  <p><h1>Help us address this imbalance.</h1></p><br>
  <%= link_to "Get started.", sample_subject_path, class: 'btn btn-primary btn-lg' %>
</div>
<div class="jumbotron" id="jumbotron-about">
  <h3>A number of great organizations are working to spread awareness about the under-representation of women on Wikipedia. We join them in highlighting the many important women in technology who deserve better representation in online encyclopedic resources.</h3>
  <h3>This site is built around data collected by the<br><a href="https://www.cs.duke.edu/csed/wikipedia/index.html" target="_blank">CRA-W and Anita Borg Institute Wikipedia Project</a>.<br><a href="https://docs.google.com/spreadsheet/ccc?key=0AgtB-ve2c_3ydDFiVkt3U3FTUXJBb0VydmRHc3FVS3c#gid=0">See their public spreadsheet.</a></h3>
</div>

app/views/subjects/index.html.erb
<div class="container">
  <div class="row">
    <br>
  </div>
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><h1><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>WOMEN WITHOUT WIKIPEDIA PAGES</h1></a>
      </div>
      <div id="collapseOne" class="panel-collapse collapse">
        <div class="panel panel-body index">
          <ul class="list-unstyled">
            <%= render partial: 'subject', collection: @subjects_without %>      
          </ul>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><h1><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>WOMEN WITH WIKIPEDIA PAGES</h1></a>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel panel-body index">
          <ul class="list-unstyled">
            <%= render partial: 'subject', collection: @subjects_with %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/new.html.erb
<h3>Add a new individual to our database!</h3>

<p>Please be mindful of spelling so that we can find information about the right person.</p>
<br>
<%= render 'form' %>

app/views/subjects/resources.html.erb
<div class="jumbotron">
  <h2>Resources</h2>
  <h3><a href="https://www.cs.duke.edu/csed/wikipedia/index.html">CRA-W and Anita Borg Institute Wikipedia Project</a></h3>
  <h3><a href="http://art.plusfeminism.org/">Art+Feminism</a></h3>
  <h3><a href="https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women%27s_History/Taskforces/Women_in_technology">WikiProject Women's History</a></h3>
  <h3><a href="http://en.wikipedia.org/wiki/Wikipedia:Your_first_article">Wikipedia:Your first article</a></h3>
</div>
<div style="text-align: center">
  <h3>Please <a href="mailto: hello@codeequality.com">reach out</a> to suggest additions to these resources.</h3>
</div>

app/views/subjects/show.html.erb
<% if flash[:message] %>
  <div class="row top-pad">
    <div class="col-md-12 col-sm-12">
      <div class="panel">
        <h1 class="flash-message text-center"><%= flash[:message] %></h1>
        <% if user_signed_in? %>
          <h1>You can <%= link_to "add this person to our database", new_subject_path %>.</h1>
          <h3>Or just check out this other awesome woman in technology!</h3>
        <% else %>
          <h1>You can <%= link_to "sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> to add this person to our database.</h1>
          <h3>Or just check out this other awesome woman in technology!</h3>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if @subject.has_wiki_page %>
  <%= render 'subject_with_wiki' %>
<% else %>
  <%= render 'subject_without_wiki' %>
<% end %>

app/views/users/_user.html.erb
<td></td>
<td><%= user.name %></td>
<td><%= link_to user.email, user %></td>
<td><%= user.sign_in_count %></td>
<td><%= user.subjects.size %></td>

app/views/users/index.html.erb
<h3>Welcome, <%= current_user.name %></h3>
<h4>You are a badass administrator.</h4>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <th>
            <td>Name</td>
            <td>Email</td>
            <td># of Times Signed In</td>
            <td># of Subjects Created</td>
          </th>
          <% @users.each do |user| %>  
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<p><%= @user.name %> has signed in <%= @user.sign_in_count %> times!</p>
<% if !@user.subjects.empty? %>
  <p><%= @user.name %> has created the following subjects in the database:</p><br>
  <ul>
    <% @user.subjects.each do |s| %>
      <li><%= link_to s.name, subject_path(s) %></li>
    <% end %>
  </ul>
<% end %>